POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

###
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "company_name": "Company name 1"
}

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "email": "partner1@user.com",
    "password": "secret",
    "address": "address test",
    "phone": "11987654321"
}

### Criação do evento pelo parceiro
POST http://localhost:3000/partners/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Evento 1 é legal",
    "date": "2025-01-21T00:00:00",
    "location": "rua x, bairro etc"
}

### Listagem de evento do parceiro
GET http://localhost:3000/partners/events

### Listagem de um evento do parceiro
GET http://localhost:3000/partners/events/1

### Listagem de eventos
GET http://localhost:3000/events

### Listagem de um evento
GET http://localhost:3000/events/1